[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
optimizer_runs=10000
via_ir=true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
